
import { SinType, Question, SinData } from './types';

export const SINS: Record<SinType, SinData> = {
  [SinType.PRIDE]: {
    type: SinType.PRIDE,
    description: "The excessive belief in one's own abilities. It is the root of all other vices, a distortion of self-worth.",
    color: 'amber-500',
    icon: 'crown',
    imageUrl: 'https://i.ibb.co/C5214hrR/Pride.png'
  },
  [SinType.GREED]: {
    type: SinType.GREED,
    description: "The insatiable desire for material gain, prioritizing possession over spiritual or human connection.",
    color: 'emerald-500',
    icon: 'coins',
    imageUrl: 'https://i.ibb.co/mVdZvCdW/Greed.png'
  },
  [SinType.LUST]: {
    type: SinType.LUST,
    description: "Unbridled sexual desire or appetite. A chaotic longing that consumes the heart and mind.",
    color: 'rose-500',
    icon: 'heart',
    imageUrl: 'https://i.ibb.co/gLS3HVhx/Lust.png'
  },
  [SinType.ENVY]: {
    type: SinType.ENVY,
    description: "Sorrow for another's good. The bitterness felt when observing the success or status of others.",
    color: 'indigo-500',
    icon: 'eye',
    imageUrl: 'https://i.ibb.co/fGdXXgZc/Envy.png'
  },
  [SinType.GLUTTONY]: {
    type: SinType.GLUTTONY,
    description: "Inordinate consumption beyond requirement. An addiction to sensory excess and overindulgence.",
    color: 'orange-500',
    icon: 'utensils',
    imageUrl: 'https://i.ibb.co/vxXgP0bV/Gluttony.png'
  },
  [SinType.WRATH]: {
    type: SinType.WRATH,
    description: "Uncontrolled fury and the rejection of love for retaliation. A destructive flame that burns from within.",
    color: 'red-600',
    icon: 'flame',
    imageUrl: 'https://i.ibb.co/Ngm6h8HN/Wrath.png'
  },
  [SinType.SLOTH]: {
    type: SinType.SLOTH,
    description: "The avoidance of spiritual or physical work. A state of apathy, laziness, and spiritual stagnation.",
    color: 'sky-500',
    icon: 'moon',
    imageUrl: 'https://i.ibb.co/TqNXJSDS/Sloth.png'
  }
};

export const QUESTIONS: Question[] = [
  { id: 1, sin: SinType.PRIDE, text: "I often compare my achievements to those of others and feel superior." },
  { id: 2, sin: SinType.GREED, text: "I feel a sense of satisfaction when I acquire new possessions." },
  { id: 3, sin: SinType.WRATH, text: "I have trouble controlling my temper when provoked." },
  { id: 4, sin: SinType.ENVY, text: "I wish I had the lifestyle of someone I see on social media." },
  { id: 5, sin: SinType.LUST, text: "I frequently daydream about romantic or sexual scenarios." },
  { id: 6, sin: SinType.GLUTTONY, text: "I tend to overeat during meals, even when I'm full." },
  { id: 7, sin: SinType.SLOTH, text: "I put off tasks until the last minute, even if they are important." },
  { id: 8, sin: SinType.PRIDE, text: "I believe that my opinions are usually correct and others should listen to me." },
  { id: 9, sin: SinType.GREED, text: "I feel anxious if I don't have money saved for the future." },
  { id: 10, sin: SinType.WRATH, text: "I hold grudges against people who have wronged me." },
  { id: 11, sin: SinType.ENVY, text: "I feel jealous when a friend receives praise or recognition." },
  { id: 12, sin: SinType.LUST, text: "I often find myself staring at attractive strangers." },
  { id: 13, sin: SinType.GLUTTONY, text: "I consume more entertainment than I should, neglecting other responsibilities." },
  { id: 14, sin: SinType.SLOTH, text: "I avoid strenuous activities and prefer to relax whenever possible." },
  { id: 15, sin: SinType.PRIDE, text: "I take pride in knowing that I am more skilled than my peers." },
  { id: 16, sin: SinType.GREED, text: "I often think about how to make more money, even at the expense of leisure time." },
  { id: 17, sin: SinType.WRATH, text: "I have yelled at someone in anger within the past month." },
  { id: 18, sin: SinType.ENVY, text: "I feel discontented when I see others with newer gadgets than mine." },
  { id: 19, sin: SinType.LUST, text: "I have made decisions based solely on physical attraction." },
  { id: 20, sin: SinType.GLUTTONY, text: "I buy more food than I can eat, leading to waste." },
  { id: 21, sin: SinType.SLOTH, text: "I skip workouts or exercise routines because I lack motivation." },
  { id: 22, sin: SinType.PRIDE, text: "I rarely admit when I am wrong in an argument." },
  { id: 23, sin: SinType.GREED, text: "I hoard items because I might need them someday, even if I don't." },
  { id: 24, sin: SinType.WRATH, text: "I have broken something out of anger." },
  { id: 25, sin: SinType.ENVY, text: "I secretly celebrate when a rival fails." },
  { id: 26, sin: SinType.LUST, text: "I spend time browsing dating apps or websites without intending to meet anyone." },
  { id: 27, sin: SinType.GLUTTONY, text: "I drink alcohol to the point of intoxication regularly." },
  { id: 28, sin: SinType.SLOTH, text: "I neglect household chores until they become overwhelming." },
  { id: 29, sin: SinType.PRIDE, text: "I feel that I deserve special treatment because of my accomplishments." },
  { id: 30, sin: SinType.GREED, text: "I am reluctant to share my belongings with others." },
  { id: 31, sin: SinType.WRATH, text: "I have violent thoughts when I am extremely upset." },
  { id: 32, sin: SinType.ENVY, text: "I mimic the style of someone I admire to gain similar attention." },
  { id: 33, sin: SinType.LUST, text: "I prioritize sexual gratification over emotional connection in relationships." },
  { id: 34, sin: SinType.GLUTTONY, text: "I indulge in sugary snacks despite knowing they are unhealthy." },
  { id: 35, sin: SinType.SLOTH, text: "I spend hours on the couch watching TV instead of being productive." },
  { id: 36, sin: SinType.PRIDE, text: "I often talk about my own successes in conversations." },
  { id: 37, sin: SinType.GREED, text: "I check my bank account frequently to see my balance grow." },
  { id: 38, sin: SinType.WRATH, text: "I feel a rush of adrenaline when I argue with someone." },
  { id: 39, sin: SinType.ENVY, text: "I buy things just because my friends have them." },
  { id: 40, sin: SinType.LUST, text: "I have engaged in flirtatious behavior with someone in a committed relationship." },
  { id: 41, sin: SinType.GLUTTONY, text: "I eat quickly without savoring the taste of my food." },
  { id: 42, sin: SinType.SLOTH, text: "I delay responding to emails or messages because I find them tedious." },
  { id: 43, sin: SinType.PRIDE, text: "I look down on people who make less money than I do." },
  { id: 44, sin: SinType.GREED, text: "I negotiate aggressively to get the best deal, even with friends." },
  { id: 45, sin: SinType.WRATH, text: "I replay past conflicts in my mind and imagine retaliating." },
  { id: 46, sin: SinType.ENVY, text: "I feel a pang of resentment when I see couples in happy relationships." },
  { id: 47, sin: SinType.LUST, text: "I watch pornography frequently." },
  { id: 48, sin: SinType.GLUTTONY, text: "I order multiple dishes at restaurants to try them all, but can't finish." },
  { id: 49, sin: SinType.SLOTH, text: "I hit the snooze button multiple times every morning." },
  { id: 50, sin: SinType.PRIDE, text: "I expect others to acknowledge my contributions without prompting." },
  { id: 51, sin: SinType.GREED, text: "I feel unsatisfied with my current salary, no matter how much I earn." },
  { id: 52, sin: SinType.WRATH, text: "I have spoken harshly to a loved one during a disagreement." },
  { id: 53, sin: SinType.ENVY, text: "I wish I had the fame and recognition of a celebrity." },
  { id: 54, sin: SinType.LUST, text: "I dress provocatively to attract attention from others." },
  { id: 55, sin: SinType.GLUTTONY, text: "I consume large portions of food even when I am not hungry." },
  { id: 56, sin: SinType.SLOTH, text: "I avoid starting new projects because they seem too difficult." },
  { id: 57, sin: SinType.PRIDE, text: "I believe that my way of doing things is the best way." },
  { id: 58, sin: SinType.GREED, text: "I donate less to charity than I could afford." },
  { id: 59, sin: SinType.WRATH, text: "I have road rage when driving." },
  { id: 60, sin: SinType.ENVY, text: "I feel inadequate when I see others traveling to exotic places." },
  { id: 61, sin: SinType.LUST, text: "I have one-night stands without considering the emotional consequences." },
  { id: 62, sin: SinType.GLUTTONY, text: "I stockpile snacks and junk food in my home." },
  { id: 63, sin: SinType.SLOTH, text: "I procrastinate on making important decisions." },
  { id: 64, sin: SinType.PRIDE, text: "I rarely ask for help because I prefer to rely on myself." },
  { id: 65, sin: SinType.GREED, text: "I invest time in side hustles primarily for financial gain." },
  { id: 66, sin: SinType.WRATH, text: "I struggle to forgive people who have offended me." },
  { id: 67, sin: SinType.ENVY, text: "I compare my physical appearance to others and feel dissatisfied." },
  { id: 68, sin: SinType.LUST, text: "I use dating apps primarily for casual hookups." },
  { id: 69, sin: SinType.GLUTTONY, text: "I binge-watch TV series for entire weekends." },
  { id: 70, sin: SinType.SLOTH, text: "I leave tasks unfinished because I lose interest quickly." },
  { id: 71, sin: SinType.PRIDE, text: "I enjoy being the center of attention in social gatherings." },
  { id: 72, sin: SinType.GREED, text: "I shop for sales even when I don't need anything." },
  { id: 73, sin: SinType.WRATH, text: "I have a list of people I consider enemies." },
  { id: 74, sin: SinType.ENVY, text: "I feel bitter when someone else gets the promotion I wanted." },
  { id: 75, sin: SinType.LUST, text: "I think about sex multiple times a day." },
  { id: 76, sin: SinType.GLUTTONY, text: "I eat until I feel physically uncomfortable." },
  { id: 77, sin: SinType.SLOTH, text: "I spend more time planning than actually doing." },
  { id: 78, sin: SinType.PRIDE, text: "I dismiss advice from others because I think I know better." },
  { id: 79, sin: SinType.GREED, text: "I save money excessively, even forgoing basic comforts." },
  { id: 80, sin: SinType.WRATH, text: "I enjoy debates because I like proving others wrong." },
  { id: 81, sin: SinType.ENVY, text: "I feel jealous of my sibling's relationship with our parents." },
  { id: 82, sin: SinType.LUST, text: "I have cheated on a partner because I was attracted to someone else." },
  { id: 83, sin: SinType.GLUTTONY, text: "I drink caffeine excessively to stay awake, ignoring health effects." },
  { id: 84, sin: SinType.SLOTH, text: "I neglect personal hygiene when I am feeling lazy." },
  { id: 85, sin: SinType.PRIDE, text: "I take credit for group projects without acknowledging others." },
  { id: 86, sin: SinType.GREED, text: "I gamble with the hope of winning big money." },
  { id: 87, sin: SinType.WRATH, text: "I have punched a wall or thrown objects in anger." },
  { id: 88, sin: SinType.ENVY, text: "I wish I had the talent of a famous musician or artist." },
  { id: 89, sin: SinType.LUST, text: "I have sent explicit messages to someone I barely know." },
  { id: 90, sin: SinType.GLUTTONY, text: "I buy expensive foods as a status symbol." },
  { id: 91, sin: SinType.SLOTH, text: "I sleep in late on weekends, wasting the day." },
  { id: 92, sin: SinType.PRIDE, text: "I believe that my social status is important to my identity." },
  { id: 93, sin: SinType.GREED, text: "I collect items that I never use, just for the sake of owning them." },
  { id: 94, sin: SinType.WRATH, text: "I have threatened someone in a fit of rage." },
  { id: 95, sin: SinType.ENVY, text: "I feel envious of people who have more friends than I do." },
  { id: 96, sin: SinType.LUST, text: "I have used charm to manipulate others into sexual encounters." },
  { id: 97, sin: SinType.GLUTTONY, text: "I eat out of boredom rather than hunger." },
  { id: 98, sin: SinType.SLOTH, text: "I avoid volunteering because it requires too much effort." },
  { id: 99, sin: SinType.PRIDE, text: "I expect praise for my efforts even when they are minimal." },
  { id: 100, sin: SinType.GREED, text: "I prioritize work over family to earn more money." }
];
